version: '3.7'

services:
  db:
    container_name: db
    image: postgres

  api-service:
    container_name: api-service
    build:
      context: ../trifold-api
      dockerfile: Dockerfile-local
      args:
        - DJANGO_SECRET_KEY
        - CLIENT_ID
    volumes:
      - ../trifold-api:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY
      - CLIENT_ID
    env_file: ../trifold-api/.env
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile-local
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api-service
      - web-service
    links:
      - api-service
      - web-service

  web-service:
    container_name: web-service
    build:
      context: ../trifold-client
      dockerfile: Dockerfile-local
      args:
        - REACT_APP_OAUTH_CLIENT_ID
    volumes:
      - ../trifold-client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - REACT_APP_OAUTH_CLIENT_ID
    env_file: ../trifold-client/.env
    depends_on:
      - api-service