version: '3.7'

services:
  db:
    container_name: db
    image: postgres

  api-service:
    container_name: api-service
    build:
      context: https://github.com/jdecked/trifold-api.git
      args:
        - DJANGO_SECRET_KEY
        - CLIENT_ID
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENVIRONMENT=production
      - DJANGO_SECRET_KEY
      - CLIENT_ID
    depends_on:
      - db
    command: gunicorn wsgi:application --log-file -

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api-service
      - web-service
    links:
      - api-service
      - web-service

  web-service:
    container_name: web-service
    build:
      context: https://github.com/jdecked/trifold-client.git
      args:
        - REACT_APP_OAUTH_CLIENT_ID
    ports:
      - "9000:9000"
    environment:
      - REACT_APP_OAUTH_CLIENT_ID
    depends_on:
      - api-service
