version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql
    hostname: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 5432:5432
    restart: always

  api-service:
    container_name: api-service
    build:
      context: ../trifold-api
      args:
        - DJANGO_SECRET_KEY
    volumes:
      - '../trifold-api:/usr/src/app'
    ports:
      - '8000:8000'
    environment:
      - DJANGO_SECRET_KEY
    env_file: ../trifold-api/.env
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      - api-service
      - web-service
    links:
      - api-service
      - web-service

  web-service:
    container_name: web-service
    build:
      context: ../trifold-client
      dockerfile: Dockerfile-local
    volumes:
      - '../trifold-client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '9000:9000'
    environment:
      - NODE_ENV=development
      - HTTPS=true
    depends_on:
      - api-service