version: '3.7'

services:
  db:
    image: mysql
    ports:
      - "5432:5432"
    healthcheck:
      test: exit 0

  api-service:
    container_name: api-service
    build:
      context: https://github.com/jdecked/trifold-api.git
    expose:
      - '5000'
    environment:
      - DATABASE_URL=mysql://root@db:5432/trifold_staging
      - DATABASE_TEST_URL=mysql://root@db:5432/trifold_test
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ENVIRONMENT=production
    depends_on:
      - db
    links:
      - db
    command: gunicorn --certfile config/ssl/development/localhost-cert.pem --keyfile config/ssl/development/localhost-key.pem --ca-cert config/ssl/development/ca-cert.pem wsgi --log-file -

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      - api-service
      - web-service
    links:
      - api-service
      - web-service

  web-service:
    container_name: web-service
    build:
      context: https://github.com/jdecked/trifold-client.git
      args:
        - NODE_ENV=development
        - HTTPS=true
    ports:
      - '9000:9000'
    depends_on:
      - api-service
    links:
      - api-service
