version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql
    hostname: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 5433:5433
    restart: always

  api-service:
    container_name: api-service
    build:
      context: https://github.com/jdecked/trifold-api.git
      args:
        - DJANGO_SECRET_KEY
    ports:
      - 8000:8000
    environment:
      - DJANGO_ENVIRONMENT=production
      - DJANGO_SECRET_KEY
    depends_on:
      - mysql
    command: gunicorn --certfile config/ssl/development/localhost-cert.pem --keyfile config/ssl/development/localhost-key.pem --ca-cert config/ssl/development/ca-cert.pem wsgi:application --log-file -

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api-service
      - web-service
    links:
      - api-service
      - web-service

  web-service:
    container_name: web-service
    build:
      context: https://github.com/jdecked/trifold-client.git
      args:
        - NODE_ENV=development
        - HTTPS=true
    ports:
      - 9000:9000
    environment:
      - NODE_ENV=development
      - HTTPS=true
    depends_on:
      - api-service
