version: '3.7'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "5432:5432"

  api-service:
    container_name: api-service
    build:
      context: https://github.com/jdecked/trifold-api.git
      args:
        - DJANGO_SECRET_KEY
    expose:
      - '5000'
    environment:
      - DJANGO_ENVIRONMENT=production
      - DJANGO_SECRET_KEY
    depends_on:
      - db
    links:
      - db
    command: gunicorn --certfile config/ssl/development/localhost-cert.pem --keyfile config/ssl/development/localhost-key.pem --ca-cert config/ssl/development/ca-cert.pem wsgi --log-file -

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      - api-service
      - web-service
    links:
      - api-service
      - web-service

  web-service:
    container_name: web-service
    build:
      context: https://github.com/jdecked/trifold-client.git
      args:
        - NODE_ENV=development
        - HTTPS=true
    ports:
      - '9000:9000'
    environment:
      - NODE_ENV=development
      - HTTPS=true
    depends_on:
      - api-service
    links:
      - api-service
