version: '3.7'

services:
  db:
    image: mysql
    ports:
      - "5432:5432" # expose ports - HOST:CONTAINER
    healthcheck:
      test: exit 0

  api-service:
    container_name: api-service
    build:
      context: ../trifold-api
      dockerfile: Dockerfile-local
    volumes:
      - '../trifold-api:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - DATABASE_URL=mysql://root@db:5432/trifold_dev
      - DJANGO_SECRET_KEY=haha_fake_key
      - DJANGO_ENVIRONMENT=development
    depends_on:
      - db
    links:
      - db

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      - api-service
      - web-service
    links:
      - api-service
      - web-service

  web-service:
    container_name: web-service
    build:
      context: ../trifold-client
      dockerfile: Dockerfile-local
    volumes:
      - '../trifold-client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
      - HTTPS=true
    depends_on:
      - api-service
    links:
      - api-service