DROP DATABASE IF EXISTS trifold;
DROP DATABASE IF EXISTS trifold_staging;
DROP DATABASE IF EXISTS trifold_dev;
DROP DATABASE IF EXISTS trifold_test;

CREATE DATABASE
IF NOT EXISTS trifold;
CREATE DATABASE
IF NOT EXISTS trifold_staging;
CREATE DATABASE
IF NOT EXISTS trifold_dev;
CREATE DATABASE
IF NOT EXISTS trifold_test;